### ISSUE TITLE
gulp

### ISSUE THREAD

**Issue by mikakane** [kfug/handson#1]
作業中リポジトリ

http://github.com/hogehoge....
- [ ] サンプルファイルの構築
- [ ] README.mdの構築
- [ ] キーノートの作成

**Comment by MATSUDAEmi** [comment]
#8 にて対応しています。 @mikakane @izuchy

**Comment by izuchy** [comment]
@MATSUDAEmi 
おつかれさまでした。
マージボタン、ぽちっておきましょうか。（うまく権限あればの話ですが）
